feat: Implement assistant API streaming
CopilotKit/CopilotKit pull request #272
Opened 2024-03-16 06:22 UTC by Bhavyajain21

/claim #266 
/fixes #266

2024-03-16 06:23 UTC, Bhavyajain21 commented
Please review @mme / @ataibarkai

2024-03-18 00:56 UTC, ataibarkai commented
@Bhavyajain21 the merge checks are failing-

To fix those, please follow the testing guide in the [contributing quickstart](https://docs.copilotkit.ai/contribute/quickstart-contribute).

Thanks!

2024-03-18 01:32 UTC, ataibarkai requested changes
Thanks for your changes-

I made a few notes

2024-03-18 01:32 UTC, ataibarkai commented on CopilotKit/packages/backend/src/lib/openai-assistant-adapter.ts
> +      const run = await this.openai.beta.threads.runs.createAndStream(threadId, {
you want to make the `createAndStream` change inside the existing `submitUserMessage` function. 

it encapsulates additional context injections and business logic

2024-03-18 01:32 UTC, ataibarkai commented on CopilotKit/packages/backend/src/lib/openai-assistant-adapter.ts
> -      run = await this.submitUserMessage(threadId, forwardedProps);
per the other comment: we want to keep this code here.
The changes should be made inside the `submitUserMessage` function definition

2024-03-18 01:32 UTC, ataibarkai commented on CopilotKit/packages/backend/src/lib/openai-assistant-adapter.ts
> +  async buildInstructions(forwardMessages: Message[]): Promise<string> {
the existing `submitUserMessage` function already performs the instruction-building and tool-building steps clearly enough, there is no need for defining these as separate functions

2024-03-18 01:32 UTC, ataibarkai commented on CopilotKit/packages/backend/src/lib/openai-assistant-adapter.ts
> +    return new Promise((resolve) => {
this implementation is on the right direction, but I believe we want to use our existing abstractions here,

see `writeChatCompletionChunk`, `writeChatCompletionEnd` and `AssistantSingleChunkReadableStream` for an example.

@mme can you chime in here please?

2024-03-22 00:24 UTC, ataibarkai commented
@Bhavyajain21 just wanted to make sure you saw this

2024-03-22 14:38 UTC, Bhavyajain21 commented
Hey @ataibarkai, will work on the reviews today!

2024-03-25 13:26 UTC, closed without merging