Feat: When there is an error response from OpenAI, display it in the chat window #267
CopilotKit/CopilotKit pull request #274
Opened 2024-03-17 05:24 UTC by VaibhavKVerma

<img width="1658" alt="Screenshot 2024-03-17 at 10 53 05 AM" src="https://github.com/CopilotKit/CopilotKit/assets/76198333/0bbaf1fa-78a1-4203-a611-eff5ccde8718">

- Handled API error
- Added the error statuxText as response in the message

2024-03-17 21:27 UTC, VaibhavKVerma commented
Please review @mme / @ataibarkai

2024-03-26 12:28 UTC, ataibarkai requested changes
Hi @VaibhavKVerma thanks for the PR.

A small change is needed. See comment.

2024-03-26 12:28 UTC, ataibarkai commented on CopilotKit/packages/backend/src/lib/openai-adapter.ts
> +      stream.on("chatCompletion", () => {
using `.on("chatCompletion"` here breaks the backend, because this trigger it's called when the stream finishes - by which point it's too late to stream

But if you replace this with `.on("connect")` it should work 
https://github.com/openai/openai-node/blob/master/helpers.md#onconnect---

2024-03-26 12:57 UTC, VaibhavKVerma commented on CopilotKit/packages/backend/src/lib/openai-adapter.ts
> +      stream.on("chatCompletion", () => {
Ok will do the changes

2024-04-06 12:01 UTC, VaibhavKVerma commented
Please review @ataibarkai

2024-04-18 18:12 UTC, ataibarkai approved these changes
looks great, thanks!

2024-04-18 18:13 UTC, merged