Added the Hacktoberfest folder called demos containing a README.md  & TEMPLATE.md
CopilotKit/CopilotKit pull request #599
Opened 2024-09-27 14:31 UTC by NathanTarbert

The `demos` folder provides detailed instructions and guidelines to help Hacktoberfest participants successfully submit their projects.

2024-09-27 14:32 UTC, NathanTarbert commented
We are still working out the messaging and steps. 

Not ready to merge

2024-09-30 15:45 UTC, arielweinberger commented on demos/CONTRIBUTING.md
> +   - **Project Title**
```suggestion
   - **Project Title**:
```

2024-09-30 15:52 UTC, arielweinberger requested changes

2024-09-30 15:52 UTC, arielweinberger commented on demos/CONTRIBUTING.md
> +1. **Copy the Template**: Navigate to the `TEMPLATE.md` file in the repository. Copy its content as the baseline for your submission.
```suggestion
1. **Copy the Template**: Navigate to the [TEMPLATE.md](./TEMPLATE.md) file in the repository. Copy its content as the baseline for your submission.
```

2024-10-01 13:26 UTC, arielweinberger approved these changes

2024-10-01 13:32 UTC, merged