Added a CONTRIBUTING.md to Guide New Contributors
CopilotKit/CopilotKit pull request #680
Opened 2024-10-03 06:42 UTC by SGCODEX

fixes #654
@NathanTarbert Sir please review

2024-10-03 14:10 UTC, NathanTarbert requested changes
A Code of Conduct has been added.

2024-10-07 04:08 UTC, Redidacove requested changes

2024-10-07 04:08 UTC, Redidacove commented on CONTRIBUTING.md
> +Fork the CopilotKit repository to your GitHub organization. This means that you'll have a copy of the repository under _your-GitHub-username/repository-name_.
It would be better if you could add an image showing where is the fork button

2024-10-07 04:08 UTC, Redidacove commented on CONTRIBUTING.md
> +git clone https://github.com/{your-GitHub-username}/CopilotKit
here as well showing screenshot of clone btn in your forked repo

2024-10-07 04:08 UTC, Redidacove commented on CONTRIBUTING.md
> +Set up and run the development environment on your local machine:
No need for this line title is self explanatory ib

2024-10-07 04:08 UTC, Redidacove commented on CONTRIBUTING.md
> +Install the dependencies using pnpm:
### 
```suggestion
To install the dependencies using pnpm
Go inside project folder and run :
```

2024-10-07 04:08 UTC, Redidacove commented on CONTRIBUTING.md
> +- for docs change : docs/{ISSUE_NUMBER}-{CUSTOM_NAME}
```suggestion
- for docs change : docs/<ISSUE_NUMBER>-<CUSTOM_NAME>
```
same with others

2024-10-07 04:08 UTC, Redidacove commented on CONTRIBUTING.md
> +git checkout -b branch-name-here
```suggestion
git checkout -b <new-branch-name-here>
```

2024-10-07 04:08 UTC, Redidacove commented on CONTRIBUTING.md
> +# Start all packages in development mode
```suggestion
# To start all packages in development mode
```

2024-10-07 04:08 UTC, Redidacove commented on CONTRIBUTING.md
> +git push origin branch-name-here
```suggestion
git push origin <branch-name-here>
```

2024-10-07 08:55 UTC, SGCODEX commented
Done the changes sir, please review @Redidacove

2024-10-07 09:58 UTC, Redidacove requested changes

2024-10-07 09:58 UTC, Redidacove commented on CONTRIBUTING.md
> +
I do think you have answered this in later section then why redirecting to discord here.
Instead can add this as faq and place this in later section

2024-10-07 09:58 UTC, Redidacove commented on CONTRIBUTING.md
> +# How do I make a code contribution?
isn't this is the answer to previous question How can I contribute you can redesign this part a bit i think

2024-10-07 09:58 UTC, Redidacove commented on CONTRIBUTING.md
> +### 1)Install Prerequisites
```suggestion
### 1) Install Prerequisites
```

2024-10-07 09:58 UTC, Redidacove commented on CONTRIBUTING.md
> +### 2)Install Dependencies
```suggestion
### 2) Install Dependencies
```
same with the rest

2024-10-07 09:58 UTC, Redidacove commented on CONTRIBUTING.md
> +## Step 8: Push the changes to the remote repository
I think you should also mention pulling the latest changes from remote before pushing to avoid conflicts

2024-10-07 09:58 UTC, Redidacove commented on CONTRIBUTING.md
> +1.  Give the pull request a title and a short description of the changes made. Include also the issue or bug number associated with your change. Explain the changes that you made, any issues you thin
```suggestion
1. Open a pull request with a title and a brief description of the changes made. Be sure to tag the associated issue or bug using #<Issue_No>. In the description, explain the changes you made, any issues you think might exist with the pull request, and any questions you have for the maintainer.
```
Plz fix the grammatical errors in your writing using some online tool.

2024-10-07 09:58 UTC, Redidacove commented on CONTRIBUTING.md
> +## Git Commit Messages
I think you should add this as well into above section inside 'Commit the changes'

2024-10-07 09:59 UTC, Redidacove commented
I am sorry for overwhelming with so many comments, but I hope it helps.

2024-10-07 14:23 UTC, NathanTarbert approved these changes

2024-10-07 14:23 UTC, merged

2024-10-07 14:24 UTC, NathanTarbert commented
Thank you @SGCODEX!

2024-10-07 14:54 UTC, SGCODEX commented
Thank you @NathanTarbert Sir for merging